import Link from "next/link";
import React from "react";

const getUsers = async () => {
	const data = await fetch("http://localhost:3000/api/users");
	const res = await data.json();
	return res;
};
export const metadata = {
	title: "Next | Users",
	description: "Generated by create next app",
};

const UsersPage = async () => {
	const users = await getUsers();

	return (
		<div>
			<ul>
				{users.map(item => (
					<li>
						<Link href={`/users/${item.id}`}>
							{item.firstName} {item.lastName}
						</Link>
					</li>
				))}
			</ul>
		</div>
	);
};

export default UsersPage;
