import Image from "next/image";
import styles from "./page.module.css";
import s from "./main.module.scss";
export const metadata = {
	title: "Next | Home",
	description: "Generated by create next app",
};
export default function Home() {
	return (
		<div>
			<h1 className={s.title}>Hello world</h1>
		</div>
	);
}
